spring:
  application:
    name: rwanda-supply-chain

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/RSCN_DB
    username: postgres
    password: 123

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

# ✅ Add this JWT configuration:
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970   # 256-bit key
    expiration-ms: 86400000   # 24 hours

    tenant:
      default-id: tenant1

server:
  port: 8082

  springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true